import { BrandLogo, brand } from "./brand.jsx";
import { AsteriskMark, HeartMark } from "./WithMarks.jsx";

const TEXT = brand.text;
const MUTED = brand.textMuted;
const BORDER = brand.border;
const SURFACE = brand.surface;
const BG = brand.bg;

function Section({ title, children }) {
  return (
    <section style={{ marginTop: 30 }}>
      <h2 style={{ fontFamily: "'Newsreader', Georgia, serif", fontSize: 24, lineHeight: 1.12, margin: "0 0 10px", fontWeight: 600 }}>{title}</h2>
      <div style={{ color: MUTED, fontSize: 14, lineHeight: 1.65 }}>{children}</div>
    </section>
  );
}

export default function PrivacyPolicy() {
  return (
    <div style={{ minHeight: "100vh", background: brand.teal, padding: "env(safe-area-inset-top) 14px env(safe-area-inset-bottom)", fontFamily: "'DM Sans', -apple-system, sans-serif" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=Newsreader:ital,opsz,wght@0,6..72,500;0,6..72,600;0,6..72,700;1,6..72,500;1,6..72,600;1,6..72,700&display=swap');
        * { box-sizing: border-box; }
        body { margin: 0; }
        a { color: ${brand.tealDark}; }
      `}</style>
      <main style={{ width: "100%", maxWidth: 720, margin: "28px auto", background: BG, color: TEXT, borderRadius: 22, overflow: "hidden", boxShadow: "0 18px 48px rgba(17,50,46,.22)" }}>
        <header style={{ background: brand.teal, padding: "26px 28px 24px", color: brand.inkOn }}>
          <BrandLogo style={{ width: 118, backgroundColor: brand.inkOn, marginBottom: 8 }} />
          <div style={{ color: "rgba(255,255,255,.76)", fontSize: 12 }}>We’re in this together.</div>
        </header>

        <article style={{ padding: "30px 28px 38px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, color: brand.tealDark, fontSize: 11, fontWeight: 800, textTransform: "uppercase", letterSpacing: ".08em", marginBottom: 10 }}>
            <HeartMark size={15} color={brand.teal} />
            Privacy
          </div>
          <h1 style={{ fontFamily: "'Newsreader', Georgia, serif", fontSize: 38, lineHeight: 1, margin: "0 0 10px", fontWeight: 600 }}>Privacy Policy</h1>
          <div style={{ color: MUTED, fontSize: 13 }}>Effective August 28, 2026</div>

          <p style={{ color: MUTED, fontSize: 15, lineHeight: 1.65, margin: "22px 0 0" }}>
            With is a private health-tracking app built around a simple idea: your health is personal, but you don’t have to do it alone. This policy explains what information With collects, why it is used, who may see it, and how you can delete it.
          </p>

          <Section title="Information you choose to give With">
            <p>Depending on how you use With, you may provide:</p>
            <ul>
              <li><strong style={{ color: TEXT }}>Account information</strong>, such as your email address, authentication information, and time zone.</li>
              <li><strong style={{ color: TEXT }}>Profile information</strong>, such as your name, personal color, Withmark, and membership in a With.</li>
              <li><strong style={{ color: TEXT }}>Health and wellness information</strong>, including weight, nutrition and food entries, calories and macronutrients, activity, calories burned, steps, water, fasting information, goals, daily targets, and intentions.</li>
              <li><strong style={{ color: TEXT }}>Shared app content</strong>, such as saved foods or other information you intentionally add for use within your With.</li>
              <li><strong style={{ color: TEXT }}>Invitation information</strong>, such as an email address you enter when inviting someone to your With.</li>
            </ul>
          </Section>

          <Section title="Information collected automatically">
            <p>
              With uses standard browser and hosting technology needed to keep you signed in and make the app work. This can include session information, local browser storage, device or browser details, IP addresses, and service logs generated by our hosting and infrastructure providers.
            </p>
            <p>With does not currently use advertising networks or third-party analytics SDKs.</p>
          </Section>

          <Section title="How With uses information">
            <p>Information is used to:</p>
            <ul>
              <li>provide, personalize, and operate the app;</li>
              <li>save and display your health information and progress;</li>
              <li>let people in the same With share the intended experience;</li>
              <li>authenticate accounts and provide password recovery;</li>
              <li>send invitations you ask With to send;</li>
              <li>protect the security and reliability of the service; and</li>
              <li>respond to support or privacy requests.</li>
            </ul>
            <p>With does not sell personal information or health information. With does not use your health information for advertising or targeted marketing.</p>
          </Section>

          <Section title="What people in your With can see">
            <p>
              With is private by default, but it is designed to be shared with a small group of people you trust. Other members of your With may see profile and health information that the app displays as part of your shared With experience. Your account remains separate, and joining a With does not cause you to inherit another person’s goals, targets, or health data.
            </p>
            <p>Do not join a With with someone you do not trust with the information the app makes visible to members.</p>
          </Section>

          <Section title="Service providers">
            <p>With relies on a small number of service providers to operate:</p>
            <ul>
              <li><strong style={{ color: TEXT }}>Supabase</strong> provides authentication, database storage, and backend services.</li>
              <li><strong style={{ color: TEXT }}>Netlify</strong> hosts and delivers the web application.</li>
              <li><strong style={{ color: TEXT }}>Resend</strong> is used to deliver invitation emails when you ask With to send one.</li>
            </ul>
            <p>These providers may process information only as needed to provide their services and are subject to their own security, privacy, and retention practices.</p>
          </Section>

          <Section title="Data security">
            <p>
              With uses account authentication, encrypted web connections, and Supabase Row Level Security to limit database access. No system can guarantee absolute security, but With is designed to keep unrelated Withs isolated from one another and to avoid exposing private health data publicly.
            </p>
          </Section>

          <Section title="Data retention and deletion">
            <p>
              With keeps your account and personal health information while your account is active so the service can provide your history and shared experience.
            </p>
            <p>
              You can delete your account from <strong style={{ color: TEXT }}>Profile → Account → Delete account</strong>. Account deletion removes your login, your personal profile, and your personal health entries. If other people remain in your With, information that belongs to the With rather than solely to you may remain for those members. Service providers may also retain limited backups or technical logs according to their own retention practices.
            </p>
          </Section>

          <Section title="Your choices">
            <p>You can:</p>
            <ul>
              <li>edit or delete many entries directly in With;</li>
              <li>change your account email, password, profile information, and time zone;</li>
              <li>leave the service by deleting your account; and</li>
              <li>contact us with questions about your information.</li>
            </ul>
          </Section>

          <Section title="Children">
            <p>With is not intended for children under 13, and we do not knowingly seek personal information from children under 13.</p>
          </Section>

          <Section title="Health information and medical care">
            <p>
              With is a personal tracking tool. It is not a healthcare provider, medical record system, or substitute for professional medical advice, diagnosis, or treatment.
            </p>
          </Section>

          <Section title="Changes to this policy">
            <p>
              If With’s data practices materially change, this policy will be updated and the effective date above will change. Material changes may also be communicated in the app when appropriate.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Privacy questions or requests can be sent to <a href="mailto:privacy@imwith.me">privacy@imwith.me</a>.
            </p>
          </Section>

          <div style={{ marginTop: 34, paddingTop: 20, borderTop: `1px solid ${BORDER}`, display: "flex", alignItems: "center", gap: 8 }}>
            <AsteriskMark size={14} color={brand.teal} />
            <a href="/" style={{ fontSize: 13, fontWeight: 800, textDecoration: "none" }}>Back to With</a>
          </div>
        </article>
      </main>
    </div>
  );
}
